[variables]
NIXPACKS_PROVIDERS = ["python"]
NIXPACKS_IGNORE_PATHS = ["cash-pot v5/", "deploy-687cc9f68045b4912ab57737/", "frontend/"]

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "uvicorn server:app --host 0.0.0.0 --port $PORT"
