[variables]
NIXPACKS_PROVIDERS = ["nodejs"]

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd frontend && npm ci"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd frontend && npx serve -s build -l 3000"
