services:
  - type: web
    name: cashpot-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: casino_management
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: CORS_ORIGINS
        value: '["https://jeka7ro.github.io", "https://jeka7ro.github.io/cashpot-v5"]'
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@cashpot.com
      - key: ADMIN_PASSWORD
        value: admin123
      - key: API_V1_STR
        value: /api
      - key: PROJECT_NAME
        value: CASHPOT Gaming Management System
